### ISSUE TITLE
Error trying to establish an HTTPS connection

### ISSUE THREAD

**Issue by cyberandy** [wordlift/llama-graphql-loader#2]
Here follows the error. It looks as if the connector tried to create a connection to the server at 'wordlift-blog.[www.localhost](http://www.localhost/)', but it couldn't resolve the server's address, leading to a socket.gaierror (this usually happens when the domain name can't be resolved to an IP address).

Since it couldn't connect to the server, the connection attempt was retried a few times (as is usual in many network operations to ensure temporary network issues don't cause failures). After the maximum number of retries was reached without a successful connection, a urllib3.exceptions.MaxRetryError was thrown.

The error was caught and a requests.exceptions.ConnectionError was thrown, indicating that the request library couldn't establish a connection to the server.

Finally, a DataTransformError was raised, which is a custom exception defined in the code you're running. This error was raised because of the earlier connection error.

```
ERROR:root:Error transforming data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wordlift-blog.www.localhost', port=443): Max retries exceeded with url: /blog/en/seo-automation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py", line 133, in transform_data
    if is_url(value) and is_valid_html(value):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py", line 218, in is_valid_html
    response = requests.get(content)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wordlift-blog.www.localhost', port=443): Max retries exceeded with url: /blog/en/seo-automation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR:root:Error loading data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wordlift-blog.www.localhost', port=443): Max retries exceeded with url: /blog/en/seo-automation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py", line 133, in transform_data
    if is_url(value) and is_valid_html(value):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py", line 218, in is_valid_html
    response = requests.get(content)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wordlift-blog.www.localhost', port=443): Max retries exceeded with url: /blog/en/seo-automation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py", line 155, in load_data
    documents = self.transform_data(data)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py", line 144, in transform_data
    raise DataTransformError('Error transforming data') from e
custom_loader.DataTransformError: Error transforming data
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/urllib3/connection.py in _new_conn(self)
    173         try:
--> 174             conn = connection.create_connection(
    175                 (self._dns_host, self.port), self.timeout, **extra_kw

19 frames
gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPSConnectionPool(host='wordlift-blog.www.localhost', port=443): Max retries exceeded with url: /blog/en/seo-automation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
ConnectionError: HTTPSConnectionPool(host='wordlift-blog.www.localhost', port=443): Max retries exceeded with url: /blog/en/seo-automation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x787f2b516a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

The above exception was the direct cause of the following exception:

DataTransformError                        Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/llama_index/readers/llamahub_modules/wordlift/base.py in transform_data(self, data)
    142         except Exception as e:
    143             logging.error('Error transforming data:', exc_info=True)
--> 144             raise DataTransformError('Error transforming data') from e
    145 
    146     def load_data(self) -> List[Document]:

DataTransformError: Error transforming data
```

**Comment by cyberandy** [comment]
This has been fixed.
